name: PF2e System CD

on:
  workflow_dispatch:
    branches: [v13-dev]

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Build JSON packs
        run: npm run build:packs:json

      - name: Update Manifest
        run: |
          SYSTEM_VERSION=$(grep -oP '(?<="version": ")[^"]+' dist/pf2e/system.json | tr -d '\n')
          perl -pi -E "s|latest/download/pf2e\\.zip|download/$SYSTEM_VERSION/pf2e.zip|" dist/pf2e/system.json
          echo "systemVersion=$SYSTEM_VERSION" >> $GITHUB_ENV

      - name: Zip Files
        working-directory: ./dist/pf2e
        run: zip -r ./system.zip ./*

      - name: Zip JSON Assets
        working-directory: ./json-assets
        run: |
          cp -r ../static/lang/ ./
          zip -r ./json-assets.zip ./*

      - name: Create Version Release
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.systemVersion }} (pf2e)
          allowUpdates: false
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./dist/pf2e/system.json,./dist/pf2e/system.zip,./json-assets/json-assets.zip"
          tag: pf2e-${{ env.systemVersion }}
